// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8ZrhIhlI2UXu6IFq1GnQp3cciNNxnWyo',
    appId: '1:57869567989:web:8713453937100c455782bc',
    messagingSenderId: '57869567989',
    projectId: 'app-boleiros',
    authDomain: 'app-boleiros.firebaseapp.com',
    databaseURL: 'https://app-boleiros-default-rtdb.firebaseio.com',
    storageBucket: 'app-boleiros.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8GfbKnIw2IRSVp2TeKifzPLnP-fx16Mc',
    appId: '1:57869567989:android:de54e53ac01b3e745782bc',
    messagingSenderId: '57869567989',
    projectId: 'app-boleiros',
    databaseURL: 'https://app-boleiros-default-rtdb.firebaseio.com',
    storageBucket: 'app-boleiros.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRCtvlpim2ygpLhLXI5Xd8yKLWuXwkAZw',
    appId: '1:57869567989:ios:8ac78c871306df8f5782bc',
    messagingSenderId: '57869567989',
    projectId: 'app-boleiros',
    databaseURL: 'https://app-boleiros-default-rtdb.firebaseio.com',
    storageBucket: 'app-boleiros.appspot.com',
    iosBundleId: 'com.example.appFutebol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8ZrhIhlI2UXu6IFq1GnQp3cciNNxnWyo',
    appId: '1:57869567989:web:6b71ae91ad588b235782bc',
    messagingSenderId: '57869567989',
    projectId: 'app-boleiros',
    authDomain: 'app-boleiros.firebaseapp.com',
    databaseURL: 'https://app-boleiros-default-rtdb.firebaseio.com',
    storageBucket: 'app-boleiros.appspot.com',
  );
}
